/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include "stable_part_provider.h"

#include "common/om2/codegen/om2_codegen_types.h"

namespace ge {
Status ResolveStablePart(StablePartId id, std::string &output) {
  switch (id) {
    case StablePartId::kChkStatusMacro:
      output =
          "#define OM2_CHK_STATUS(expr, ...)            \\\n"
          "do {                                       \\\n"
          "  const aclError _chk_status = (expr);     \\\n"
          "  if (_chk_status != ACL_SUCCESS) {        \\\n"
          "    return _chk_status;                    \\\n"
          "  }                                        \\\n"
          "} while (false)\n";
      return SUCCESS;
    case StablePartId::kChkNotNullMacro:
      output =
          "#define OM2_CHK_NOTNULL(ptr, ...)            \\\n"
          "do {                                       \\\n"
          "  if ((ptr) == nullptr) {                  \\\n"
          "    return ACL_ERROR_FAILURE;              \\\n"
          "  }                                        \\\n"
          "} while (false)\n";
      return SUCCESS;
    case StablePartId::kChkTrueMacro:
      output =
          "#define OM2_CHK_TRUE(expr, ...)              \\\n"
          "do {                                       \\\n"
          "  if (!(expr)) {                           \\\n"
          "    return ACL_ERROR_FAILURE;              \\\n"
          "  }                                        \\\n"
          "} while (false)\n";
      return SUCCESS;
    case StablePartId::kGetAddrMacro:
      output =
          "#define GET_ADDR(mem_ptr, offset)   \\\n"
          "(reinterpret_cast<void *>(                 \\\n"
          "  reinterpret_cast<uintptr_t>(mem_ptr) +   \\\n"
          "  static_cast<uintptr_t>(offset)))\n";
      return SUCCESS;
    case StablePartId::kMakeGuardMacro:
      output = "#define OM2_MAKE_GUARD(var, callback) const ::om2::ScopeGuard const_guard_##var(callback)\n";
      return SUCCESS;
    case StablePartId::kInterfaceMacros:
      output =
          "#define OM2_CHK_STATUS(expr, ...)            \\\n"
          "do {                                       \\\n"
          "  const aclError _chk_status = (expr);     \\\n"
          "  if (_chk_status != ACL_SUCCESS) {        \\\n"
          "    OM2_LOGE(__VA_ARGS__);                 \\\n"
          "    return _chk_status;                    \\\n"
          "  }                                        \\\n"
          "} while (false)\n"
          "\n"
          "#define OM2_CHK_NOTNULL(ptr, ...)            \\\n"
          "do {                                       \\\n"
          "  if ((ptr) == nullptr) {                  \\\n"
          "    OM2_LOGE(__VA_ARGS__);                 \\\n"
          "    return ACL_ERROR_FAILURE;              \\\n"
          "  }                                        \\\n"
          "} while (false)\n"
          "\n"
          "#define OM2_CHK_TRUE(expr, ...)              \\\n"
          "do {                                       \\\n"
          "  if (!(expr)) {                           \\\n"
          "    OM2_LOGE(__VA_ARGS__);                 \\\n"
          "    return ACL_ERROR_FAILURE;              \\\n"
          "  }                                        \\\n"
          "} while (false)\n"
          "\n"
          "#define OM2_CHK_RT(expr, ...)               \\\n"
          "do {                                       \\\n"
          "  const rtError_t _rt_err = (expr);        \\\n"
          "  if (_rt_err != RT_ERROR_NONE) {          \\\n"
          "    OM2_LOGE(__VA_ARGS__);                 \\\n"
          "    return ACL_ERROR_FAILURE;              \\\n"
          "  }                                        \\\n"
          "} while (false)\n"
          "\n"
          "#define GET_ADDR(mem_ptr, offset)   \\\n"
          "(reinterpret_cast<void *>(                 \\\n"
          "  reinterpret_cast<uintptr_t>(mem_ptr) +   \\\n"
          "  static_cast<uintptr_t>(offset)))\n"
          "\n"
          "#define OM2_MAKE_GUARD(var, callback) const ::om2::ScopeGuard const_guard_##var(callback)\n";
      return SUCCESS;
    case StablePartId::kPointerHelpers:
      output =
          "template<typename T>\n"
          "inline T *PtrAdd(T *const ptr, const size_t max_buf_len, const size_t idx) {\n"
          "  if ((ptr != nullptr) && (idx < max_buf_len)) {\n"
          "    return reinterpret_cast<T *>(ptr + idx);\n"
          "  }\n"
          "  return nullptr;\n"
          "}\n"
          "template<typename TI, typename TO>\n"
          "inline TO *PtrToPtr(TI *const ptr) {\n"
          "  return reinterpret_cast<TO *>(ptr);\n"
          "}\n"
          "inline uint64_t PtrToValue(const void *const ptr) {\n"
          "  return static_cast<uint64_t>(reinterpret_cast<uintptr_t>(ptr));\n"
          "}\n"
          "inline void *ValueToPtr(const uint64_t value) {\n"
          "  return reinterpret_cast<void *>(static_cast<uintptr_t>(value));\n"
          "}\n"
          "\n";
      return SUCCESS;
    case StablePartId::kInterfacePointerHelpers:
      output =
          "template<typename T>\n"
          "inline T *PtrAdd(T *const ptr, const size_t max_buf_len, const size_t idx) {\n"
          "  if ((ptr != nullptr) && (idx < max_buf_len)) {\n"
          "    return reinterpret_cast<T *>(ptr + idx);\n"
          "  }\n"
          "  return nullptr;\n"
          "}\n"
          "template<typename TI, typename TO>\n"
          "inline TO *PtrToPtr(TI *const ptr) {\n"
          "  return reinterpret_cast<TO *>(ptr);\n"
          "}\n"
          "inline uint64_t PtrToValue(const void *const ptr) {\n"
          "  return static_cast<uint64_t>(reinterpret_cast<uintptr_t>(ptr));\n"
          "}\n"
          "inline void *ValueToPtr(const uint64_t value) {\n"
          "  return reinterpret_cast<void *>(static_cast<uintptr_t>(value));\n"
          "}\n"
          "inline uint64_t PtrToU64(const void *ptr) {\n"
          "  return static_cast<uint64_t>(reinterpret_cast<uintptr_t>(ptr));\n"
          "}\n"
          "\n"
          "inline void *ResolveOpAddr(uint32_t mem_src, uint32_t index, uint64_t offset,\n"
          "                          void *total_dev_mem_ptr, void *session_scope_mem_ptr,\n"
          "                          void **constants, void **var_addrs) {\n"
          "  void *base_ptr;\n"
          "  switch (mem_src) {\n"
          "    case 1U:  // MEM_SRC_SESSION\n"
          "      base_ptr = session_scope_mem_ptr;\n"
          "      break;\n"
          "    case 2U:  // MEM_SRC_CONST\n"
          "      return constants[index];\n"
          "    case 3U:  // MEM_SRC_VAR\n"
          "      return GET_ADDR(var_addrs[index], offset);\n"
          "    default:  // MEM_SRC_DEVICE (0)\n"
          "      base_ptr = total_dev_mem_ptr;\n"
          "      break;\n"
          "  }\n"
          "  return GET_ADDR(base_ptr, offset);\n"
          "}\n"
          "\n"
          "template<typename... Args>\n"
          "inline std::vector<uint64_t> FlattenHostArgs(Args&&... args) {\n"
          "  std::vector<uint64_t> buf;\n"
          "  auto append_arg = [&](auto&& arg) {\n"
          "    using T = std::decay_t<decltype(arg)>;\n"
          "    if constexpr (std::is_pointer_v<T>) {\n"
          "      buf.push_back(reinterpret_cast<uint64_t>(arg));\n"
          "    } else if constexpr (std::is_same_v<T, gert::Tensor>) {\n"
          "      buf.push_back(reinterpret_cast<uint64_t>(arg.GetAddr()));\n"
          "    } else if constexpr (std::is_same_v<T, std::vector<int64_t>>) {\n"
          "      for (auto d : arg) buf.push_back(static_cast<uint64_t>(d));\n"
          "    } else if constexpr (std::is_integral_v<T>) {\n"
          "      buf.push_back(static_cast<uint64_t>(arg));\n"
          "    } else {\n"
          "      static_assert(sizeof(T) == 0, \"Unsupported type in FlattenHostArgs\");\n"
          "    }\n"
          "  };\n"
          "  (append_arg(std::forward<Args>(args)), ...);\n"
          "  return buf;\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kFlattenHostArgs:
      output =
          "template<typename... Args>\n"
          "inline std::vector<uint64_t> FlattenHostArgs(Args&&... args) {\n"
          "  std::vector<uint64_t> buf;\n"
          "  auto append_arg = [&](auto&& arg) {\n"
          "    using T = std::decay_t<decltype(arg)>;\n"
          "    if constexpr (std::is_pointer_v<T>) {\n"
          "      buf.push_back(reinterpret_cast<uint64_t>(arg));\n"
          "    } else if constexpr (std::is_same_v<T, gert::Tensor>) {\n"
          "      buf.push_back(reinterpret_cast<uint64_t>(arg.GetAddr()));\n"
          "    } else if constexpr (std::is_same_v<T, std::vector<int64_t>>) {\n"
          "      for (auto d : arg) buf.push_back(static_cast<uint64_t>(d));\n"
          "    } else if constexpr (std::is_integral_v<T>) {\n"
          "      buf.push_back(static_cast<uint64_t>(arg));\n"
          "    } else {\n"
          "      static_assert(sizeof(T) == 0, \"Unsupported type in FlattenHostArgs\");\n"
          "    }\n"
          "  };\n"
          "  (append_arg(std::forward<Args>(args)), ...);\n"
          "  return buf;\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kScopeGuard:
      output =
          "class ScopeGuard {\n"
          "  public:\n"
          "    ScopeGuard(const ScopeGuard &) = delete;\n"
          "    ScopeGuard &operator=(const ScopeGuard &) = delete;\n"
          "\n"
          "    explicit ScopeGuard(const std::function<void()> &on_exit_scope)\n"
          "        : on_exit_scope_(on_exit_scope) {}\n"
          "\n"
          "    ~ScopeGuard() {\n"
          "      if (on_exit_scope_) {\n"
          "        try {\n"
          "          on_exit_scope_();\n"
          "        } catch (std::bad_function_call &) {\n"
          "        } catch (...) {\n"
          "        }\n"
          "      }\n"
          "    }\n"
          "\n"
          "  private:\n"
          "    std::function<void()> on_exit_scope_;\n"
          "};\n";
      return SUCCESS;
    case StablePartId::kReadBinaryFileToBuffer:
      output =
          "BinaryBuffer ReadBinaryFileToBuffer(const std::string &file_path) {\n"
          "  BinaryBuffer result;\n"
          "  std::ifstream file(file_path, std::ios::binary | std::ios::ate);\n"
          "  if (!file.is_open()) {\n"
          "    return result;\n"
          "  }\n"
          "  std::streamsize file_size = file.tellg();\n"
          "  if (file_size <= 0) {\n"
          "    return result;\n"
          "  }\n"
          "  result.size = static_cast<size_t>(file_size);\n"
          "  result.data = std::make_unique<uint8_t[]>(result.size);\n"
          "  file.seekg(0, std::ios::beg);\n"
          "  file.read(reinterpret_cast<char *>(result.data.get()), result.size);\n"
          "  if (!file.good()) {\n"
          "    file.close();\n"
          "    result.data.reset();\n"
          "    result.size = 0;\n"
          "  }\n"
          "  return result;\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kGenerateJsonFile:
      output =
          "aclError GenerateJsonFile(const AicpuRegisterInfo &register_info, std::string &json_path) {\n"
          "  using namespace std::chrono;\n"
          "  int64_t cur_timestamp = duration_cast<milliseconds>(steady_clock::now().time_since_epoch()).count();\n"
          "  json_path = \"/tmp/temp_ops_info_\" + std::to_string(cur_timestamp) + \".json\";\n"
          "  std::string json_data_format = R\"(\n"
          "{\n"
          "    \"%s\":{\n"
          "        \"opInfo\":{\n"
          "            \"opKernelLib\":\"%s\",\n"
          "            \"kernelSo\":\"%s\",\n"
          "            \"functionName\":\"%s\"\n"
          "        }\n"
          "    }\n"
          "}\n"
          ")\";\n"
          "  char json_data[kMaxJsonFileLen];\n"
          "  auto ret = snprintf_s(json_data, kMaxJsonFileLen, kMaxJsonFileLen - 1U, json_data_format.c_str(),\n"
          "                        register_info.op_type, register_info.op_kernel_lib, register_info.so_name,\n"
          "                        register_info.kernel_name);\n"
          "  OM2_CHK_TRUE(ret >= 0);\n"
          "  std::ofstream ofs(json_path.c_str(), std::ios::trunc);\n"
          "  OM2_CHK_TRUE(ofs);\n"
          "  ofs << json_data;\n"
          "  return ACL_SUCCESS;\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kLoadAndRunExternalApis:
      output =
          "aclError Om2ModelCreate(GertModelHandle *model_handle, aclmdlRI *rt_model_handle, "
          "const char **bin_files, const void **bin_data, uint64_t *bin_size, size_t bin_num, void **constants, "
          "void **var_addrs, void *work_ptr, uint64_t *session_id, uint32_t model_id, void *instance_handle, "
          "const GertModelLoadCallbacks *callbacks, int32_t priority, uint64_t reuse_zero_copy, aclmdlRI "
          "external_rt_model, "
          "aclrtStream *external_streams, uint64_t external_stream_num, "
          "aclrtNotify *external_notifies, uint64_t external_notify_num, "
          "aclrtEvent *external_events, uint64_t external_event_num, "
          "aclrtLabel *external_labels, uint64_t external_label_num) {\n"
          "  OM2_LOGI(\"Om2ModelCreate\");\n"
          "  if ((model_handle == nullptr) || (rt_model_handle == nullptr) || (*model_handle != nullptr)) {\n"
          "    OM2_LOGE(\"Om2ModelCreate: invalid handle\");\n"
          "    return ACL_ERROR_FAILURE;\n"
          "  }\n"
          "  auto *obj = new om2::Om2Model(bin_files, bin_data, bin_size, bin_num, constants, var_addrs, "
          "work_ptr, session_id, model_id, instance_handle, callbacks, priority);\n"
          "  if (obj == nullptr) {\n"
          "    OM2_LOGE(\"Om2ModelCreate: new Om2Model failed\");\n"
          "    return ACL_ERROR_FAILURE;\n"
          "  }\n"
          "  auto ret = obj->InitResources(reuse_zero_copy, {sizeof(GertModelExternalResources), external_rt_model, "
          "external_streams, external_stream_num, external_notifies, external_notify_num, "
          "external_events, external_event_num, external_labels, external_label_num});\n"
          "  if (ret != ACL_SUCCESS) {\n"
          "    OM2_LOGE(\"Om2ModelCreate: InitResources failed, ret: %d\", ret);\n"
          "    delete obj;\n"
          "    return ret;\n"
          "  }\n"
          "  ret = obj->RegisterKernels();\n"
          "  if (ret != ACL_SUCCESS) {\n"
          "    OM2_LOGE(\"Om2ModelCreate: RegisterKernels failed, ret: %d\", ret);\n"
          "    delete obj;\n"
          "    return ret;\n"
          "  }\n"
          "  *model_handle = reinterpret_cast<GertModelHandle>(obj);\n"
          "  *rt_model_handle = obj->GetRtModelHandle();\n"
          "  OM2_LOGI(\"Om2ModelCreate done\");\n"
          "  return ACL_SUCCESS;\n"
          "}\n"
          "\n"
          "aclError Om2ModelLoad(GertModelHandle *model_handle) {\n"
          "  OM2_LOGI(\"Om2ModelLoad\");\n"
          "  if ((model_handle == nullptr) || (*model_handle == nullptr)) {\n"
          "    OM2_LOGE(\"Om2ModelLoad: invalid handle\");\n"
          "    return ACL_ERROR_FAILURE;\n"
          "  }\n"
          "  return static_cast<om2::Om2Model*>(*model_handle)->Load(nullptr);\n"
          "}\n"
          "\n"
          "aclError Om2ModelRunAsync(GertModelHandle *model_handle, aclrtStream stream, int input_count, "
          "gert::Tensor **input_data, int output_count, gert::Tensor **output_data, "
          "const GertModelRunCallbacks *run_callbacks) {\n"
          "  OM2_LOGI(\"Om2ModelRunAsync\");\n"
          "  return static_cast<om2::Om2Model*>(*model_handle)->RunAsync(stream, input_count, input_data, "
          "output_count, "
          "output_data, run_callbacks);\n"
          "}\n"
          "\n"
          "aclError Om2ModelRun(GertModelHandle *model_handle, int input_count, gert::Tensor **input_data, int "
          "output_count, "
          "gert::Tensor **output_data, int32_t stream_sync_timeout, const GertModelRunCallbacks *run_callbacks) {\n"
          "  OM2_LOGI(\"Om2ModelRun\");\n"
          "  return static_cast<om2::Om2Model*>(*model_handle)->Run(input_count, input_data, output_count, "
          "output_data, stream_sync_timeout, run_callbacks);\n"
          "}\n"
          "\n"
          "aclError Om2ModelDestroy(GertModelHandle *model_handle) {\n"
          "  OM2_LOGI(\"Om2ModelDestroy\");\n"
          "  delete static_cast<om2::Om2Model*>(*model_handle);\n"
          "  return ACL_SUCCESS;\n"
          "}\n"
          "\n"
          "// ==================== model load/run/unload api ====================\n"
          "\n"
          "int32_t GertModelLoad(const struct GertModelLoadConfig *config, GertModelHandle *model_handle,\n"
          "                      struct GertModelLoadOutput *output) {\n"
          "  if ((model_handle == nullptr) || (*model_handle != nullptr) || (config == nullptr)) {\n"
          "    OM2_LOGE(\"GertModelLoad: invalid handle or config\");\n"
          "    return ACL_ERROR_FAILURE;\n"
          "  }\n"
          "  if (output != nullptr) {\n"
          "    OM2_LOGE(\"GertModelLoad: output is reserved, should be null\");\n"
          "    return ACL_ERROR_FAILURE;\n"
          "  }\n"
          "  aclmdlRI rt_model_handle;\n"
          "  // Create Model\n"
          "  OM2_CHK_STATUS(Om2ModelCreate(model_handle, &rt_model_handle, config->bin_files, config->bin_data,\n"
          "                                config->bin_size, static_cast<size_t>(config->bin_num), config->constants,\n"
          "                                config->var_addrs, config->work_ptr, config->session_id,\n"
          "                                static_cast<uint32_t>(config->model_id), config->instance_handle,\n"
          "                                config->callbacks,\n"
          "                                static_cast<int32_t>(config->priority), config->reuse_zero_copy,\n"
          "                                config->external_rt_model,\n"
          "                                config->external_streams, config->external_stream_num,\n"
          "                                config->external_notifies, config->external_notify_num,\n"
          "                                config->external_events, config->external_event_num,\n"
          "                                config->external_labels, config->external_label_num));\n"
          "  OM2_LOGI(\"GertModelLoad: handle=%p, model_id=%\" PRIu64 \", priority=%\" PRIi64 \",\"\n"
          "           \" bin_num=%\" PRIu64 \"\", *model_handle, config->model_id,\n"
          "           config->priority, config->bin_num);\n"
          "  // Load Model\n"
          "  return static_cast<om2::Om2Model *>(*model_handle)->Load(config->callbacks);\n"
          "}\n"
          "\n"
          "int32_t GertModelRunAsync(GertModelHandle model_handle, aclrtStream stream,\n"
          "                          const struct GertModelRunConfig *config, struct GertModelRunOutput *output) {\n"
          "  if ((model_handle == nullptr) || (config == nullptr)) {\n"
          "    OM2_LOGE(\"GertModelRunAsync: invalid handle or config\");\n"
          "    return ACL_ERROR_FAILURE;\n"
          "  }\n"
          "  OM2_LOGI(\"GertModelRunAsync: handle=%p, stream=%p, input_count=%\" PRIu64 \",\"\n"
          "           \" output_count=%\" PRIu64 \"\", model_handle, stream, config->input_count,\n"
          "           config->output_count);\n"
          "  const GertModelRunCallbacks *run_callbacks = (config == nullptr ? nullptr : config->run_callbacks);\n"
          "  return Om2ModelRunAsync(&model_handle, stream, config->input_count, config->input_data, "
          "config->output_count,\n"
          "                          config->output_data, run_callbacks);\n"
          "}\n"
          "\n"
          "int32_t GertModelRun(GertModelHandle model_handle, const struct GertModelRunConfig *config,\n"
          "                     struct GertModelRunOutput *output) {\n"
          "  if ((model_handle == nullptr) || (config == nullptr)) {\n"
          "    OM2_LOGE(\"GertModelRun: invalid handle or config\");\n"
          "    return ACL_ERROR_FAILURE;\n"
          "  }\n"
          "  OM2_LOGI(\"GertModelRun: handle=%p, stream_sync_timeout_ms=%\" PRIu64 \",\"\n"
          "           \" input_count=%\" PRIu64 \", output_count=%\" PRIu64 \"\", model_handle,\n"
          "           config->stream_sync_timeout_ms, config->input_count, config->output_count);\n"
          "  const GertModelRunCallbacks *run_callbacks = (config == nullptr ? nullptr : config->run_callbacks);\n"
          "  return Om2ModelRun(&model_handle, config->input_count, config->input_data, config->output_count,\n"
          "                     config->output_data, config->stream_sync_timeout_ms, run_callbacks);\n"
          "}\n"
          "\n"
          "int32_t GertModelUnload(GertModelHandle model_handle, const struct GertModelUnloadConfig *config,\n"
          "                        struct GertModelUnloadOutput *output) {\n"
          "  if (model_handle == nullptr) {\n"
          "    OM2_LOGE(\"GertModelUnload: invalid handle\");\n"
          "    return ACL_ERROR_FAILURE;\n"
          "  }\n"
          "  if ((config != nullptr) || (output != nullptr)) {\n"
          "    OM2_LOGE(\"GertModelUnload: config and output are reserved, should be null\");\n"
          "    return ACL_ERROR_FAILURE;\n"
          "  }\n"
          "  OM2_LOGI(\"GertModelUnload: handle=%p\", model_handle);\n"
          "  return Om2ModelDestroy(&model_handle);\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kInterfaceDumpApis:
      output =
          "struct GertModelTaskIoEntry {\n"
          "  uint64_t struct_size = sizeof(GertModelTaskIoEntry);\n"
          "  const gert::Tensor *tensor = nullptr;\n"
          "  uint64_t offset = 0;\n"
          "};\n"
          "\n"
          "enum GertModelArgKind : uint64_t {\n"
          "  GERT_MODEL_ARG_INPUT = 0,\n"
          "  GERT_MODEL_ARG_OUTPUT = 1,\n"
          "  GERT_MODEL_ARG_WORKSPACE = 2,\n"
          "  GERT_MODEL_ARG_TILING = 3,\n"
          "  GERT_MODEL_ARG_SHAPE_INFO = 4,\n"
          "  GERT_MODEL_ARG_LEVEL1_DESC = 5,\n"
          "  GERT_MODEL_ARG_PLACEHOLDER = 6,\n"
          "  GERT_MODEL_ARG_CUSTOM_VALUE = 7,\n"
          "  GERT_MODEL_ARG_FFTS_ADDR = 8,\n"
          "  GERT_MODEL_ARG_EVENT_ADDR = 9,\n"
          "  GERT_MODEL_ARG_OVERFLOW_ADDR = 10,\n"
          "  GERT_MODEL_ARG_EMPTY_ADDR = 11,\n"
          "  GERT_MODEL_ARG_INVALID_KIND = 0xFFFFU\n"
          "};\n"
          "\n"
          "struct GertModelArgSlotInfo {\n"
          "  uint64_t struct_size = sizeof(GertModelArgSlotInfo);\n"
          "  GertModelArgKind kind = GERT_MODEL_ARG_INVALID_KIND;\n"
          "  uint64_t flags = 0;\n"
          "  uint64_t args_offset = 0;\n"
          "  uint64_t value = 0;\n"
          "  uint64_t related_index = 0;\n"
          "  uint64_t event_id = 0;\n"
          "  uint64_t level1_target_offset = 0;\n"
          "};\n"
          "\n"
          "struct GertModelTaskRawInfo {\n"
          "  uint64_t struct_size = sizeof(GertModelTaskRawInfo);\n"
          "  uint64_t need_assert_or_printf = 0;\n"
          "  uint64_t arg_num = 0;\n"
          "  const struct GertModelArgSlotInfo *args = nullptr;\n"
          "};\n"
          "\n"
          "struct GertModelTaskDesc {\n"
          "  uint64_t struct_size = sizeof(GertModelTaskDesc);\n"
          "  const char *op_name = nullptr;\n"
          "  const char *op_type = nullptr;\n"
          "  uint64_t task_id = 0;\n"
          "  uint64_t stream_id = 0;\n"
          "  uint64_t context_id = 0;\n"
          "  uint64_t thread_id = 0;\n"
          "  uint64_t block_dim = 0;\n"
          "  uint64_t op_desc_id = 0;\n"
          "  uintptr_t args_base = 0;\n"
          "  uint64_t args_size = 0;\n"
          "  uint64_t input_num = 0;\n"
          "  const struct GertModelTaskIoEntry *inputs = nullptr;\n"
          "  uint64_t output_num = 0;\n"
          "  const struct GertModelTaskIoEntry *outputs = nullptr;\n"
          "  uint64_t workspace_num = 0;\n"
          "  const uint64_t *workspace_addrs = nullptr;\n"
          "  const uint64_t *workspace_sizes = nullptr;\n"
          "  uint64_t task_type = 0;\n"
          "  uint64_t kernel_type = 10000U;\n"
          "  void *stream = nullptr;\n"
          "  uint64_t is_raw_address = 0;\n"
          "  const struct GertModelTaskRawInfo *task_raw_info = nullptr;\n"
          "  uint64_t launch_begin = 0;\n"
          "  const char *original_op_names = nullptr;\n"
          "  uint64_t input_mem_size = 0;\n"
          "  uint64_t output_mem_size = 0;\n"
          "  uint64_t workspace_mem_size = 0;\n"
          "  uint64_t weight_mem_size = 0;\n"
          "};\n"
          "\n"
          "struct GertModelBaseInfo {\n"
          "  uint64_t struct_size = sizeof(GertModelBaseInfo);\n"
          "  const void *rt_model_handle = nullptr;\n"
          "};\n"
          "\n"
          "using ReportModelBaseInfoFunc = int32_t (*)(void *instance_handle, const struct GertModelBaseInfo *info);\n"
          "\n"
          "enum GertModelTaskLaunchType : uint64_t {\n"
          "  ACL_RT_LAUNCH_KERNEL_V2 = 0,\n"
          "  RT_STARS_TASK_LAUNCH_WITH_FLAG = 1,\n"
          "};\n"
          "\n"
          "struct GertModelLaunchKernelV2Params {\n"
          "  uint64_t struct_size = sizeof(GertModelLaunchKernelV2Params);\n"
          "  aclrtFuncHandle func_handle = nullptr;\n"
          "  uint32_t block_dim = 0;\n"
          "  // 用于填充空洞，保持结构体布局与 ACL 接口一致。\n"
          "  uint32_t reserved_1 = 0;\n"
          "  const void *args_data = nullptr;\n"
          "  size_t args_size = 0;\n"
          "  aclrtLaunchKernelCfg *config = nullptr;\n"
          "  aclrtStream stream = nullptr;\n"
          "};\n"
          "\n"
          "struct GertModelLaunchStarsTaskWithFlagParams {\n"
          "  uint64_t struct_size = sizeof(GertModelLaunchStarsTaskWithFlagParams);\n"
          "  const void *task_sqe = nullptr;\n"
          "  uint32_t sqe_len = 0;\n"
          "  // 用于填充空洞，保持结构体布局与 ACL 接口一致。\n"
          "  uint32_t reserved_1 = 0;\n"
          "  aclrtStream stream = nullptr;\n"
          "  uint32_t flag = 0;\n"
          "  // 用于填充空洞，保持结构体布局与 ACL 接口一致。\n"
          "  uint32_t reserved_2 = 0;\n"
          "};\n"
          "\n"
          "union GertModelTaskLaunchParams {\n"
          "  GertModelLaunchKernelV2Params launch_kernel_v2_params;\n"
          "  GertModelLaunchStarsTaskWithFlagParams launch_stars_task_params;\n"
          "};\n"
          "\n"
          "struct GertModelTaskLaunchInfo {\n"
          "  uint64_t struct_size = sizeof(GertModelTaskLaunchInfo);\n"
          "  GertModelTaskLaunchType launch_type = ACL_RT_LAUNCH_KERNEL_V2;\n"
          "  GertModelTaskDesc *task_info = nullptr;\n"
          "  const GertModelTaskLaunchParams *launch_params = nullptr;\n"
          "};\n"
          "\n"
          "using GertModelLaunchFunc = int32_t (*)(void *instance_handle, GertModelTaskLaunchInfo *launch_info);\n"
          "using LockBinHandleStoreFunc = int32_t (*)();\n"
          "using UnlockBinHandleStoreFunc = int32_t (*)();\n"
          "using QueryBinHandleFromStoreFunc = int32_t (*)(const char *bin_id, aclrtBinHandle *bin_handle);\n"
          "using SaveBinHandleToStoreFunc = int32_t (*)(const char *bin_id, aclrtBinHandle bin_handle);\n"
          "using ReleaseBinHandleFromStoreFunc = int32_t (*)(const char *bin_id, uint8_t *need_unload);\n"
          "\n"
          "struct GertModelLoadCallbacks {\n"
          "  uint64_t struct_size = sizeof(GertModelLoadCallbacks);\n"
          "  ReportModelBaseInfoFunc report_model_base_info = nullptr;\n"
          "  GertModelLaunchFunc launch_func = nullptr;\n"
          "  LockBinHandleStoreFunc lock_bin_handle_store = nullptr;\n"
          "  UnlockBinHandleStoreFunc unlock_bin_handle_store = nullptr;\n"
          "  QueryBinHandleFromStoreFunc query_bin_handle_from_store = nullptr;\n"
          "  SaveBinHandleToStoreFunc save_bin_handle_to_store = nullptr;\n"
          "  ReleaseBinHandleFromStoreFunc release_bin_handle_from_store = nullptr;\n"
          "};\n"
          "\n"
          "using ReportModelRunFunc = int32_t (*)(void *instance_handle, const struct GertModelRunReportInfo "
          "*info);\n"
          "\n"
          "struct GertModelRunReportInfo {\n"
          "  uint64_t struct_size = sizeof(GertModelRunReportInfo);\n"
          "  uint64_t model_id = 0;\n"
          "  aclrtStream stream = nullptr;\n"
          "  uint64_t is_async = 0;\n"
          "};\n"
          "\n"
          "struct GertModelRunCallbacks {\n"
          "  uint64_t struct_size = sizeof(GertModelRunCallbacks);\n"
          "  ReportModelRunFunc report_run_info_preprocess = nullptr;\n"
          "  ReportModelRunFunc report_run_info_postprocess = nullptr;\n"
          "};\n"
          "\n"
          "struct GertModelLoadConfig {\n"
          "  uint64_t struct_size = sizeof(GertModelLoadConfig);\n"
          "  const char **bin_files = nullptr;\n"
          "  const void **bin_data = nullptr;\n"
          "  uint64_t *bin_size = nullptr;\n"
          "  uint64_t bin_num = 0;\n"
          "  void **constants = nullptr;\n"
          "  void **var_addrs = nullptr;\n"
          "  void *work_ptr = nullptr;\n"
          "  uint64_t *session_id = nullptr;\n"
          "  uint64_t model_id = 0; // used for logging\n"
          "  void *instance_handle = nullptr;\n"
          "  const struct GertModelLoadCallbacks *callbacks = nullptr;\n"
          "  int64_t priority = 0;\n"
          "  uint64_t reuse_zero_copy = 0;\n"
          "  aclmdlRI external_rt_model = nullptr;\n"
          "  aclrtStream *external_streams = nullptr;\n"
          "  uint64_t external_stream_num = 0;\n"
          "  aclrtEvent *external_events = nullptr;\n"
          "  uint64_t external_event_num = 0;\n"
          "  aclrtLabel *external_labels = nullptr;\n"
          "  uint64_t external_label_num = 0;\n"
          "  aclrtNotify *external_notifies = nullptr;\n"
          "  uint64_t external_notify_num = 0;\n"
          "};\n"
          "\n"
          "struct GertModelExternalResources {\n"
          "  uint64_t struct_size = sizeof(GertModelExternalResources);\n"
          "  aclmdlRI external_rt_model = nullptr;\n"
          "  aclrtStream *external_streams = nullptr;\n"
          "  uint64_t external_stream_num = 0;\n"
          "  aclrtNotify *external_notifies = nullptr;\n"
          "  uint64_t external_notify_num = 0;\n"
          "  aclrtEvent *external_events = nullptr;\n"
          "  uint64_t external_event_num = 0;\n"
          "  aclrtLabel *external_labels = nullptr;\n"
          "  uint64_t external_label_num = 0;\n"
          "};\n"
          "\n"
          "struct GertModelRunConfig {\n"
          "  uint64_t struct_size = sizeof(GertModelRunConfig);\n"
          "  uint64_t input_count = 0;\n"
          "  gert::Tensor **input_data = nullptr;\n"
          "  uint64_t output_count = 0;\n"
          "  gert::Tensor **output_data = nullptr;\n"
          "  uint64_t stream_sync_timeout_ms = 0;\n"
          "  const struct GertModelRunCallbacks *run_callbacks = nullptr;\n"
          "};\n"
          "\n"
          "struct GertModelUnloadConfig {\n"
          "  uint64_t struct_size = sizeof(GertModelUnloadConfig);\n"
          "};\n"
          "\n"
          "struct GertModelLoadOutput {\n"
          "  uint64_t struct_size = sizeof(GertModelLoadOutput);\n"
          "};\n"
          "\n"
          "struct GertModelRunOutput {\n"
          "  uint64_t struct_size = sizeof(GertModelRunOutput);\n"
          "};\n"
          "\n"
          "struct GertModelUnloadOutput {\n"
          "  uint64_t struct_size = sizeof(GertModelUnloadOutput);\n"
          "};\n";
      return SUCCESS;
    case StablePartId::kLoadAndRunDumpHelpers:
      output =
          "gert::Tensor BuildTensor(void *device_address, uint64_t size, int32_t data_type, int32_t format,\n"
          "                         const int64_t *shape_dims, uint64_t shape_dims_num) {\n"
          "  gert::StorageShape storage_shape;\n"
          "  for (auto i = 0U; i < shape_dims_num; ++i) {\n"
          "    auto dim = shape_dims[i];\n"
          "    (void)storage_shape.MutableStorageShape().AppendDim(dim);\n"
          "    (void)storage_shape.MutableOriginShape().AppendDim(dim);\n"
          "  }\n"
          "  gert::StorageFormat storage_format(static_cast<ge::Format>(format), static_cast<ge::Format>(format), "
          "{});\n"
          "  gert::Tensor tensor(storage_shape, storage_format, gert::kOnDeviceHbm, "
          "static_cast<ge::DataType>(data_type),\n"
          "                      reinterpret_cast<gert::TensorAddress>(device_address));\n"
          "  tensor.SetSize(size);\n"
          "\n"
          "  return tensor;\n"
          "}\n"
          "\n"
          "aclError AssembleOm2TaskInfo(GertModelTaskDesc *task_info, const char *op_name, const char *op_type,\n"
          "                             uint32_t task_id, uint32_t stream_id, uint32_t block_dim,\n"
          "                             uint64_t op_desc_id, uintptr_t args_base, uint64_t args_size,\n"
          "                             const GertModelTaskIoEntry *inputs, uint64_t input_num,\n"
          "                             const GertModelTaskIoEntry *outputs, uint32_t output_num,\n"
          "                             const uint64_t *workspace_addrs, const uint64_t *workspace_sizes,\n"
          "                             uint32_t workspace_num, uint32_t task_type, void *stream,\n"
          "                             uint32_t is_raw_address = 0U,\n"
          "                             uint64_t launch_begin = 0U,\n"
          "                             const char *original_op_names = nullptr,\n"
          "                             uint64_t input_mem_size = 0U,\n"
          "                             uint64_t output_mem_size = 0U,\n"
          "                             uint64_t workspace_mem_size = 0U,\n"
          "                             uint64_t weight_mem_size = 0U) {\n"
          "  task_info->struct_size = sizeof(GertModelTaskDesc);\n"
          "  task_info->op_name = op_name;\n"
          "  task_info->op_type = op_type;\n"
          "  task_info->task_id = task_id;\n"
          "  task_info->stream_id = stream_id;\n"
          "  task_info->context_id = 0U;\n"
          "  task_info->thread_id = static_cast<uint32_t>(mmGetTid());\n"
          "  task_info->block_dim = block_dim;\n"
          "  task_info->op_desc_id = op_desc_id;\n"
          "  task_info->args_base = args_base;\n"
          "  task_info->args_size = args_size;\n"
          "  task_info->input_num = input_num;\n"
          "  task_info->inputs = inputs;\n"
          "  task_info->output_num = output_num;\n"
          "  task_info->outputs = outputs;\n"
          "  task_info->workspace_num = workspace_num;\n"
          "  task_info->workspace_addrs = workspace_addrs;\n"
          "  task_info->workspace_sizes = workspace_sizes;\n"
          "  task_info->task_type = task_type;\n"
          "  task_info->stream = stream;\n"
          "  task_info->is_raw_address = is_raw_address;\n"
          "  task_info->task_raw_info = nullptr;\n"
          "  task_info->launch_begin = launch_begin;\n"
          "  task_info->original_op_names = original_op_names;\n"
          "  task_info->input_mem_size = input_mem_size;\n"
          "  task_info->output_mem_size = output_mem_size;\n"
          "  task_info->workspace_mem_size = workspace_mem_size;\n"
          "  task_info->weight_mem_size = weight_mem_size;\n"
          "  return ACL_SUCCESS;\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kCreateLabelListForLabelSwitch:
      output =
          "aclError Om2Model::CreateLabelListForLabelSwitch(uint32_t op_index, std::vector<uint32_t> "
          "label_list_indexs)\n"
          "{\n"
          "  label_switch_label_list_[op_index] = nullptr;\n"
          "  uint32_t label_used_size = label_list_indexs.size();\n"
          "  label_used_.resize(label_used_size, nullptr);\n"
          "  for (uint32_t i = 0; i < label_used_size; i++) {\n"
          "    label_used_[i] = label_list_[label_list_indexs[i]];\n"
          "  }\n"
          "  OM2_CHK_STATUS(aclrtCreateLabelList(label_used_.data(), label_used_.size(), "
          "&(label_switch_label_list_[op_index])));\n"
          "  return ACL_SUCCESS;\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kCreateLabelListForLabelGotoEx:
      output =
          "aclError Om2Model::CreateLabelListForLabelGotoEx(uint32_t op_index, uint32_t label_index)\n"
          "{\n"
          "  label_goto_ex_label_list_[op_index] = nullptr;\n"
          "  const auto it = label_goto_args_.find(label_index);\n"
          "  if (it != label_goto_args_.cend()) {\n"
          "    label_goto_ex_label_list_[op_index] = it->second.first;\n"
          "  } else {\n"
          "    label_used_.resize(1, nullptr);\n"
          "    label_used_[0] = label_list_[static_cast<size_t>(label_index)];\n"
          "    OM2_CHK_STATUS(aclrtCreateLabelList(label_used_.data(), label_used_.size(), "
          "&(label_goto_ex_label_list_[op_index])));\n"
          "    label_goto_args_[label_index] = {label_goto_ex_label_list_[op_index], "
          "static_cast<uint32_t>(sizeof(rtLabelDevInfo))};\n"
          "  }\n"
          "  return ACL_SUCCESS;\n"
          "}\n";
      return SUCCESS;
    case StablePartId::kOpDefStructs:
      output = OpDispatchType::ToString() +
               "\n"
               "// 算子参数类型枚举\n"
               "enum OpArgType : int32_t {\n"
               "    OP_ARG_INPUT = 0,          // 输入张量\n"
               "    OP_ARG_OUTPUT = 1,         // 输出张量\n"
               "    OP_ARG_WORKSPACE = 2,      // 工作空间\n"
               "    OP_ARG_CONST_TENSOR = 3,   // 常量张量\n"
               "    OP_ARG_LEVEL1_DESC = 4,    // Level1 描述符\n"
               "    OP_ARG_SHAPE_INFO = 5,     // Shape 信息\n"
               "    OP_ARG_CUSTOM_VALUE = 6,   // 自定义值\n"
               "    OP_ARG_PLACEHOLDER = 7,    // 占位符\n"
               "    OP_ARG_OPTIONAL_EMPTY = 8, // 可选空参数\n"
               "    OP_ARG_FFTS_ADDR = 9,      // FFTS 地址\n"
               "    OP_ARG_EVENT_ADDR = 10,    // 事件地址\n"
               "    OP_ARG_OVERFLOW_ADDR = 11, // 溢出地址\n"
               "    OP_ARG_TILING = 12,        // Tiling 数据\n"
               "    OP_ARG_RAW_ADDR = 13,      // 原始地址\n"
               "    OP_ARG_VAR_TENSOR = 14,    // 变量张量\n"
               "};\n"
               "\n"
               "// 算子参数信息结构体\n"
               "struct OpArgInfo {\n"
               "  int32_t type;                      // 参数类型（OpArgType，switch 条件）\n"
               "  struct {                           // 地址解析（INPUT/OUTPUT/WORKSPACE/CONST_TENSOR/VAR_TENSOR）\n"
               "    uint32_t mem_src;                // 内存来源（0=设备，1=session，2=常量，3=变量）\n"
               "    uint32_t index;                  // 常量/变量数组索引\n"
               "    uint64_t offset;                 // 内存偏移量\n"
               "  } addr;\n"
               "  union {\n"
               "    struct {                         // Tensor 元数据（INPUT/OUTPUT）\n"
               "      uint64_t size;                 // 数据大小（字节），WORKSPACE 也用此字段\n"
               "      int32_t data_type;             // 数据类型\n"
               "      int32_t format;                // 数据格式\n"
               "      int64_t shape[8];              // Shape 维度数组（最多8维）\n"
               "      uint32_t shape_dims;       // 实际 shape 维度数\n"
               "      uint64_t args_offset;          // args table 内字节偏移\n"
               "    } tensor;\n"
               "    uint64_t custom_value;           // 自定义值（LEVEL1_DESC/SHAPE_INFO/CUSTOM_VALUE/EVENT_ADDR）\n"
               "    struct {                         // Tiling 数据（TILING）\n"
               "      const uint8_t *raw_data;       // 原始数据指针\n"
               "      uint32_t raw_data_len;         // 原始数据长度\n"
               "    } tiling;\n"
               "  } data;\n"
               "};\n"
               "\n"
               "// CUSTOM_VALUE 写回条目\n"
               "struct CustomValueEntry {\n"
               "  uint64_t host_offset;   // args table 内字节偏移\n"
               "  uint64_t value;         // 编译期常量值\n"
               "  uint32_t size;          // 4 (uint32_t) 或 8 (uint64_t)\n"
               "};\n"
               "\n"
               "// 算子定义结构体（前置声明各 dispatch_info 子结构）\n"
               "struct AicoreDispatchInfo {\n"
               "  const OpArgInfo *args_info;          // IO 地址解析数组\n"
               "  uint32_t args_info_num;      // args_info 数组长度\n"
               "  const char *op_type;        // 算子类型名，用于 Report 上报\n"
               "  uint32_t args_idx;          // 参数表索引，用于 GetArgsInfo 查找\n"
               "  uint32_t block_dim;        // Block 维度\n"
               "  uint32_t func_idx;         // 函数句柄索引，用于查找 func_handles\n"
               "  uint32_t stream_id;        // 执行流索引\n"
               "  uint32_t task_type;\n"
               "  uint32_t kernel_type;\n"
               "  struct {                    // Launch 配置，构建 LaunchKernelConfig → AssembleLaunchConfig\n"
               "    uint8_t schedule_mode;    // 调度模式\n"
               "    uint32_t engine_type;     // 引擎类型\n"
               "    uint32_t block_dim_offset;// BlockDim 偏移量\n"
               "    bool is_block_task_prefetch; // 是否预取 Block Task\n"
               "    uint16_t time_out;        // 超时时间\n"
               "    uint32_t local_memory_size;  // 本地内存大小\n"
               "  } launch;\n"
               "  struct {                    // 构建 GertModelTaskRawInfo\n"
               "    uint32_t need_assert_or_printf; // 是否需要 assert/printf\n"
               "    uint32_t slots_num;    // slot 数量\n"
               "    const GertModelArgSlotInfo *slot_info; // slot 信息数组\n"
               "  } slot_args;\n"
               "  struct {                     // 融合算子信息，非融合全为 0/nullptr\n"
               "    const char *original_op_names; // 原始算子名称（分号分隔）\n"
               "    uint64_t input_mem_size;       // 输入内存大小，字节\n"
               "    uint64_t output_mem_size;      // 输出内存大小，字节\n"
               "    uint64_t workspace_mem_size;   // workspace 内存大小，字节\n"
               "    uint64_t weight_mem_size;      // 权重内存大小，字节\n"
               "  } fusion_op;\n"
               "};\n"
               "\n"
               "struct AicpuDispatchInfo {\n"
               "  const OpArgInfo *args_info;          // IO 地址解析数组\n"
               "  uint32_t args_info_num;\n"
               "  const char *op_type;         // 算子类型名，用于 Report 上报\n"
               "  uint32_t args_idx;\n"
               "  uint32_t func_idx;\n"
               "  uint32_t block_dim;\n"
               "  uint32_t stream_id;        // 执行流索引\n"
               "  const uint8_t *args_blob;  // AICPU 参数 blob 数据\n"
               "  uint32_t args_blob_len;    // 参数 blob 长度\n"
               "  const uint8_t *ext_info_blob; // AICPU 扩展信息 blob 数据\n"
               "  uint32_t ext_info_blob_len;   // 扩展信息 blob 长度\n"
               "  struct {                    // Launch 配置\n"
               "    uint8_t schedule_mode;    // 调度模式\n"
               "    uint32_t engine_type;     // 引擎类型\n"
               "    uint32_t block_dim_offset;// BlockDim 偏移量\n"
               "    bool is_block_task_prefetch; // 是否预取 Block Task\n"
               "    uint16_t time_out;        // 超时时间\n"
               "    uint32_t local_memory_size;  // 本地内存大小\n"
               "  } launch;\n"
               "  int32_t session_info_offset;\n"
               "  uint32_t aicpu_task_index;\n"
               "  uint32_t task_type;\n"
               "  uint32_t kernel_type;\n"
               "};\n"
               "\n"
               "struct CustomDispatchInfo {\n"
               "  const OpArgInfo *args_info;  // IO 地址解析数组\n"
               "  uint32_t args_info_num;      // args_info 数组长度\n"
               "  const char *op_type;         // 算子类型名，用于 Report 上报\n"
               "  uint32_t args_idx;           // 参数表索引，用于 GetArgsInfo 查找\n"
               "  uint32_t stream_id;          // 执行流索引\n"
               "  uint32_t task_type;\n"
               "};\n"
               "\n"
               "struct DsaDispatchInfo {\n"
               "  const OpArgInfo *args_info;          // IO 地址解析数组\n"
               "  const char *op_type;         // 算子类型名，用于 Report 上报\n"
               "  uint32_t num_args;             // args 数组长度\n"
               "  int64_t op_desc_id;            // 算子描述 ID，用于 Report 上报\n"
               "  uint32_t sqe_type; uint32_t stream_id;\n"
               "  uint32_t start; uint32_t distribution_type; uint32_t data_type; uint32_t alg_type;\n"
               "  uint32_t param_vld_bitmap; uint32_t param_addr_val_bitmap;\n"
               "  uint64_t seed_value; uint32_t seed_is_addr;\n"
               "  uint64_t random_count_value; uint32_t random_count_is_addr;\n"
               "  uint64_t input1_value; uint32_t input1_is_addr;\n"
               "  uint64_t input2_value;\n"
               "  uint32_t hbm_table_index; uint32_t hbm_args_size;\n"
               "  uint32_t idx_output; uint32_t state_addr_idx;\n"
               "  uint32_t idx_seed; uint32_t idx_count;\n"
               "  uint32_t idx_input1; uint32_t idx_input2;\n"
               "  uint32_t num_iov_entries;\n"
               "  uint32_t has_input2; uint32_t task_type;\n"
               "};\n"
               "\n"
               "struct KernelExDispatchInfo {\n"
               "  const OpArgInfo *args_info;          // IO 地址解析数组\n"
               "  uint32_t args_info_num;\n"
               "  const char *op_type;         // 算子类型名，用于 Report 上报\n"
               "  uint32_t block_dim;\n"
               "  uint32_t stream_id;\n"
               "  uint32_t func_idx;\n"
               "  uint32_t tf_session_func_idx;\n"
               "  uint32_t args_table_idx;\n"
               "  const uint8_t *args_blob;\n"
               "  uint32_t args_blob_len;\n"
               "  const uint8_t *task_info_blob;\n"
               "  uint32_t task_info_blob_len;\n"
               "  const uint8_t *ext_info_blob;\n"
               "  uint32_t ext_info_blob_len;\n"
               "  struct {                    // Launch 配置\n"
               "    uint8_t schedule_mode;    // 调度模式\n"
               "    uint32_t block_dim_offset;// BlockDim 偏移量\n"
               "    bool is_block_task_prefetch; // 是否预取 Block Task\n"
               "    uint16_t time_out;        // 超时时间\n"
               "    uint32_t engine_type;     // aclrtEngineType 枚举值\n"
               "  } launch;\n"
               "  uint32_t task_type;\n"
               "};\n"
               "\n"
               "struct CmoDispatchInfo {\n"
               "  const OpArgInfo *args_info;          // src 地址解析\n"
               "  rtCmoTaskInfo_t task_info;\n"
               "  uint32_t stream_id;\n"
               "};\n"
               "\n"
               "struct MemcpyAsyncDispatchInfo {\n"
               "  const OpArgInfo *args_info;          // src/dst 地址解析\n"
               "  uint64_t dst_max;\n"
               "  uint64_t count;\n"
               "  uint32_t kind;\n"
               "  uint32_t stream_id;\n"
               "  uint32_t args_table_idx;\n"
               "  uint8_t io_refresh;\n"
               "};\n"
               "\n"
               "struct MemcpyAddrDispatchInfo {\n"
               "  const OpArgInfo *args_info;          // IO 地址解析数组\n"
               "  uint32_t args_info_num;              // args_info 数组长度\n"
               "  uint64_t dst_max;\n"
               "  uint64_t count;\n"
               "  uint32_t kind;\n"
               "  uint32_t align_offset;\n"
               "  uint32_t args_size;\n"
               "  uint32_t stream_id;\n"
               "  uint32_t args_table_idx;\n"
               "  uint32_t aligned_io_offset;\n"
               "  uint32_t num_custom_values;\n"
               "  const CustomValueEntry *custom_values;\n"
               "};\n"
               "\n"
               "struct CmoAddrDispatchInfo {\n"
               "  const OpArgInfo *args_info;          // IO 地址解析数组\n"
               "  uint32_t args_info_num;              // args_info 数组长度\n"
               "  uint32_t args_size;\n"
               "  uint32_t align_offset;\n"
               "  uint32_t cmo_op_code;\n"
               "  uint32_t stream_id;\n"
               "  uint32_t args_table_idx;\n"
               "  uint32_t io_offset;\n"
               "  uint32_t num_custom_values;\n"
               "  const CustomValueEntry *custom_values;\n"
               "};\n"
               "\n"
               "struct TaskDispatchInfo {\n"
               "  OpDispatchType dispatch_type;   // 分发类型，决定走哪个 case 分支\n"
               "  const char *op_name;            // 算子名称，用于日志和 Report 上报\n"
               "  union {\n"
               "    AicoreDispatchInfo aicore;\n"
               "    AicpuDispatchInfo aicpu;\n"
               "    CustomDispatchInfo custom;\n"
               "    CmoDispatchInfo cmo;\n"
               "    MemcpyAsyncDispatchInfo memcpy_async;\n"
               "    MemcpyAddrDispatchInfo memcpy_addr;\n"
               "    CmoAddrDispatchInfo cmo_addr;\n"
               "    DsaDispatchInfo dsa;\n"
               "    KernelExDispatchInfo kernel_ex;\n"
               "    struct { uint32_t event_id; uint32_t stream_id; } event;\n"
               "    struct { uint32_t stream_id; } fusion_start;\n"
               "    struct { uint32_t stream_id; } fusion_end;\n"
               "    struct { uint32_t stream_id; } end_graph;\n"
               "    struct { uint32_t label_index; uint32_t stream_id; } label_set;\n"
               "    struct { uint32_t notify_id; uint32_t stream_id; } notify;\n"
               "    struct { uint32_t active_stream_id; uint32_t stream_id; } stream_active;\n"
               "    struct { const OpArgInfo *args_info;          // input/value 地址解析\n"
               "             uint32_t true_stream_id; uint32_t stream_id; int32_t cond; int32_t data_type; } "
               "stream_switch;\n"
               "    struct { uint64_t op_idx; uint32_t stream_id; uint32_t memory_type; } label_goto;\n"
               "    struct { const OpArgInfo *args_info;          // input 地址解析\n"
               "             uint64_t op_idx; uint32_t branch_max; uint32_t stream_id; } label_switch;\n"
               "    struct { uint32_t stream_id; rtBarrierTaskInfo_t info; } barrier;\n"
               "  } dispatch_info;\n"
               "};\n"
               "\n"
               "// 算子分发上下文结构体\n"
               "struct DispatchOpContext {\n"
               "  void *total_dev_mem_ptr;   // 设备总内存指针\n"
               "  void *session_scope_mem_ptr; // Session 作用域内存指针\n"
               "  void **constants;          // 常量数组\n"
               "  void **var_addrs;          // 变量地址数组\n"
               "  Om2ArgsTable &args_table;  // 参数表\n"
               "  aclrtFuncHandle *func_handles; // 函数句柄数组\n"
               "  uint32_t model_id;         // 模型 ID\n"
               "  void *instance_handle;     // 实例句柄\n"
               "  aclmdlRI model_handle;     // 模型句柄\n"
               "  const std::vector<aclrtEvent> &event_list; // 事件列表\n"
               "  std::map<uint32_t, void *> &event_id_mem_map; // 事件 ID 到内存的映射\n"
               "  std::vector<void *> &dev_dynamic_mem_ptrs; // 设备动态内存指针列表\n"
               "  void *overflow_addr;       // 溢出地址\n"
               "  // --- 新增列表引用 ---\n"
               "  std::vector<void *> &label_list; // 标签列表\n"
               "  std::vector<void *> &notify_list; // 通知列表\n"
               "  std::vector<aclrtStream> &stream_list; // 流列表\n"
               "  std::map<uint32_t, std::pair<void *, uint32_t>> &label_goto_args; // 标签跳转参数\n"
               "  std::map<uint32_t, aclrtLabelList> &label_goto_ex_label_list; // 标签跳转扩展标签列表\n"
               "  std::map<uint32_t, aclrtLabelList> &label_switch_label_list; // 标签切换标签列表\n"
               "  uint64_t *session_id;        // Session ID\n"
               "  std::vector<void *> &dev_ext_info_mem_ptrs; // AICPU 扩展信息设备内存指针列表\n"
               "  uint64_t *kernel_id;        // AICPU Kernel ID 计数器\n"
               "  GertModelLaunchFunc launch_func; // 任务 launch 回调\n"
               "};\n"
               "\n";
      return SUCCESS;
    case StablePartId::kOm2LogMacros:
      output =
          "// OM2 Logging Macros\n"
          "#define OM2_MODULE_NAME static_cast<int32_t>(GE)\n"
          "#define OM2_LOG_HEADER \"OM2\"\n"
          "\n"
          "static inline uint64_t Om2GetTid() {\n"
          "#ifdef __GNUC__\n"
          "  return static_cast<uint64_t>(syscall(__NR_gettid));\n"
          "#else\n"
          "  return static_cast<uint64_t>(GetCurrentThreadId());\n"
          "#endif\n"
          "}\n"
          "\n"
          "static inline bool Om2IsLogEnable(int32_t level) {\n"
          "  return CheckLogLevel(OM2_MODULE_NAME, level) == 1;\n"
          "}\n"
          "\n"
          "#define OM2_LOGD(fmt, ...) \\\n"
          "  do { \\\n"
          "    if (Om2IsLogEnable(DLOG_DEBUG)) { \\\n"
          "      DlogRecord(OM2_MODULE_NAME, DLOG_DEBUG, \"[%s:%d] %\" PRIu64 \" [%s] %s: \" fmt, \\\n"
          "                 DLOG_FILE_NAME, __LINE__, Om2GetTid(), OM2_LOG_HEADER, __FUNCTION__, ##__VA_ARGS__); \\\n"
          "    } \\\n"
          "  } while (false)\n"
          "\n"
          "#define OM2_LOGI(fmt, ...) \\\n"
          "  do { \\\n"
          "    if (Om2IsLogEnable(DLOG_INFO)) { \\\n"
          "      DlogRecord(OM2_MODULE_NAME, DLOG_INFO, \"[%s:%d] %\" PRIu64 \" [%s] %s: \" fmt, \\\n"
          "                 DLOG_FILE_NAME, __LINE__, Om2GetTid(), OM2_LOG_HEADER, __FUNCTION__, ##__VA_ARGS__); \\\n"
          "    } \\\n"
          "  } while (false)\n"
          "\n"
          "#define OM2_LOGW(fmt, ...) \\\n"
          "  do { \\\n"
          "    if (Om2IsLogEnable(DLOG_WARN)) { \\\n"
          "      DlogRecord(OM2_MODULE_NAME, DLOG_WARN, \"[%s:%d] %\" PRIu64 \" [%s] %s: \" fmt, \\\n"
          "                 DLOG_FILE_NAME, __LINE__, Om2GetTid(), OM2_LOG_HEADER, __FUNCTION__, ##__VA_ARGS__); \\\n"
          "    } \\\n"
          "  } while (false)\n"
          "\n"
          "#define OM2_LOGE(fmt, ...) \\\n"
          "  do { \\\n"
          "    if (Om2IsLogEnable(DLOG_ERROR)) { \\\n"
          "      DlogRecord(OM2_MODULE_NAME, DLOG_ERROR, \"[%s:%d] %\" PRIu64 \" [%s] %s: \" fmt, \\\n"
          "                 DLOG_FILE_NAME, __LINE__, Om2GetTid(), OM2_LOG_HEADER, __FUNCTION__, ##__VA_ARGS__); \\\n"
          "    } \\\n"
          "  } while (false)\n";
      return SUCCESS;
    case StablePartId::kCreateClassCustomOpFactory:
      output =
          "class CustomOpFactory {\n"
          " public:\n"
          "  static graphStatus RegisterCustomOpCreator(const AscendString &op_type, const BaseOpCreator "
          "&op_creator);\n"
          "  static BaseCustomOp *CreateOrGetCustomOp(const AscendString &op_type);\n"
          "  static graphStatus GetAllRegisteredOps(std::vector<AscendString> &all_registered_ops);\n"
          "  static bool IsExistOp(const AscendString &op_type);\n"
          "  static graphStatus LoadCustomOpsPartition(const uint8_t *data, size_t len);\n"
          "};\n";
      return SUCCESS;
    case StablePartId::kCustomTaskHelpers:
      output =
          "class CustKernelContextHolder {\n"
          " public:\n"
          "  CustKernelContextHolder() = default;\n"
          "  CustKernelContextHolder(CustKernelContextHolder &&holder) {\n"
          "    context_holder_ = std::move(holder.context_holder_);\n"
          "    value_holder_ = std::move(holder.value_holder_);\n"
          "    compute_node_extend_holder_ = std::move(holder.compute_node_extend_holder_);\n"
          "    context_ = holder.context_;\n"
          "    holder.context_ = nullptr;\n"
          "  }\n"
          "\n"
          "  CustKernelContextHolder &operator=(CustKernelContextHolder &&holder) {\n"
          "    context_holder_ = std::move(holder.context_holder_);\n"
          "    value_holder_ = std::move(holder.value_holder_);\n"
          "    compute_node_extend_holder_ = std::move(holder.compute_node_extend_holder_);\n"
          "    context_ = holder.context_;\n"
          "    holder.context_ = nullptr;\n"
          "    return *this;\n"
          "  }\n"
          "\n"
          "  ~CustKernelContextHolder() {\n"
          "    for (auto &value : value_holder_) {\n"
          "      value.Set(nullptr, nullptr);\n"
          "    }\n"
          "  }\n"
          "\n"
          "  std::unique_ptr<uint8_t[]> context_holder_;\n"
          "  std::vector<gert::Chain> value_holder_;\n"
          "  std::unique_ptr<uint8_t[]> compute_node_extend_holder_;\n"
          "  gert::KernelContext *context_;\n"
          "};\n"
          "\n"
          "CustKernelContextHolder BuildKernelContextHolder(const char_t *op_name, const char_t *op_type,\n"
          "                                                 const std::vector<gert::Tensor*> &inputs,\n"
          "                                                 const std::vector<gert::Tensor*> &outputs,\n"
          "                                                 void *allocator, void *stream) {\n"
          "  std::vector<std::pair<void *, gert::Chain::Deleter>> holder_inputs;\n"
          "  std::vector<std::pair<void *, gert::Chain::Deleter>> holder_outputs;\n"
          "  std::vector<void *> ws_vec;\n"
          "  for (auto &elem : inputs) {\n"
          "    holder_inputs.emplace_back(const_cast<gert::Tensor *>(elem), nullptr);\n"
          "  }\n"
          "  holder_inputs.emplace_back(allocator, nullptr);\n"
          "  holder_inputs.emplace_back(stream, nullptr);\n"
          "  for (auto &elem : outputs) {\n"
          "    holder_outputs.emplace_back(const_cast<gert::Tensor *>(elem), nullptr);\n"
          "  }\n"
          "  holder_outputs.emplace_back(&ws_vec, nullptr);\n"
          "\n"
          "  CustKernelContextHolder holder;\n"
          "  size_t context_size =\n"
          "      sizeof(KernelRunContext) + sizeof(gert::Chain *) * (holder_inputs.size() + holder_outputs.size());\n"
          "  holder.context_holder_ = std::make_unique<uint8_t[]>(context_size);\n"
          "  if (holder.context_holder_ == nullptr) {\n"
          "    printf(\"Create context holder failed.\");\n"
          "    return holder;\n"
          "  }\n"
          "  holder.context_ = PtrToPtr<uint8_t, gert::KernelContext>(holder.context_holder_.get());\n"
          "\n"
          "  holder.compute_node_extend_holder_ = std::make_unique<uint8_t[]>(sizeof(gert::ComputeNodeInfo));\n"
          "  if (holder.compute_node_extend_holder_ == nullptr) {\n"
          "    printf(\"Create compute node holder failed.\");\n"
          "    return holder;\n"
          "  }\n"
          "  auto compute_node_info =\n"
          "      PtrToPtr<uint8_t, gert::ComputeNodeInfo>(holder.compute_node_extend_holder_.get());\n"
          "  compute_node_info->Init(inputs.size(), inputs.size(), outputs.size(), op_name, op_type);\n"
          "\n"
          "  auto kernel_run_context = holder.context_->GetContext();\n"
          "  kernel_run_context->input_size = holder_inputs.size();\n"
          "  kernel_run_context->output_size = holder_outputs.size();\n"
          "  kernel_run_context->compute_node_info = compute_node_info;\n"
          "  kernel_run_context->output_start = &(kernel_run_context->values[kernel_run_context->input_size]);\n"
          "  holder.value_holder_.resize(holder_inputs.size() + holder_outputs.size());\n"
          "  for (size_t i = 0UL; i < holder.value_holder_.size(); ++i) {\n"
          "    kernel_run_context->values[i] = PtrToPtr<gert::Chain, AsyncAnyValue>(&holder.value_holder_[i]);\n"
          "  }\n"
          "  for (size_t i = 0UL; i < holder_inputs.size(); ++i) {\n"
          "    holder.value_holder_[i].Set(holder_inputs[i].first, holder_inputs[i].second);\n"
          "  }\n"
          "  for (size_t i = 0UL; i < holder_outputs.size(); ++i) {\n"
          "    holder.value_holder_[holder_inputs.size() + i].Set(holder_outputs[i].first,\n"
          "                                                       holder_outputs[i].second);\n"
          "  }\n"
          "\n"
          "  return holder;\n"
          "}\n"
          "\n"
          "class AllocatorFaker : public gert::GertAllocator {\n"
          "  gert::GertMemBlock *Malloc(size_t /* size */) override {\n"
          "    return nullptr;\n"
          "  }\n"
          "  void Free(gert::GertMemBlock * /* block */) override {}\n"
          "  gert::GertTensorData MallocTensorData(size_t /* size */) override {\n"
          "    return gert::GertTensorData();\n"
          "  }\n"
          "  gert::TensorData MallocTensorDataFromL1(size_t /* size */) override {\n"
          "    return gert::TensorData();\n"
          "  }\n"
          "  ge::graphStatus ShareFromTensorData(const gert::TensorData & /* td */, gert::GertTensorData & /* gtd */) "
          "override {\n"
          "    return 0;\n"
          "  }\n"
          "  ge::graphStatus SetL1Allocator(ge::Allocator * /* allocator */) override {\n"
          "    return ge::GRAPH_SUCCESS;\n"
          "  }\n"
          "  ge::graphStatus FreeAt(int64_t /* stream_id */, gert::GertMemBlock * /* block */) override {\n"
          "    return ge::GRAPH_SUCCESS;\n"
          "  }\n"
          "  int64_t GetStreamNum() override {\n"
          "    return 0;\n"
          "  }\n"
          "};\n"
          "\n"
          "aclError KernelCustTaskDistribute(const char_t *op_name, const char_t *op_type, const "
          "std::vector<gert::Tensor*> &inputs,\n"
          "                                  const std::vector<gert::Tensor*> &outputs, aclrtStream stream) {\n"
          "  auto allocator = std::make_shared<AllocatorFaker>();\n"
          "  auto eager_context_holder =\n"
          "      BuildKernelContextHolder(op_name, op_type, inputs, outputs, allocator.get(), stream);\n"
          "  auto eager_context = reinterpret_cast<gert::EagerOpExecutionContext *>(eager_context_holder.context_);\n"
          "  auto custom_op_ptr = ge::CustomOpFactory::CreateOrGetCustomOp(op_type);\n"
          "  OM2_CHK_NOTNULL(custom_op_ptr);\n"
          "  auto *eager_execute_op_ptr = dynamic_cast<ge::EagerExecuteOp *>(custom_op_ptr);\n"
          "  if (eager_execute_op_ptr == nullptr) {\n"
          "    OM2_LOGE(\"%s is custom op but did not implement EagerExecuteOp\", eager_context->GetNodeType());\n"
          "    return ACL_ERROR_FAILURE;\n"
          "  }\n"
          "  OM2_CHK_STATUS(eager_execute_op_ptr->Execute(eager_context));\n"
          "\n"
          "  return ACL_SUCCESS;\n"
          "}\n"
          "\n"
          "aclError DeserializeCustKernelBinaries(std::unordered_map<std::string, BinDataInfo> &bin_info_map) {\n"
          "  for (auto &[name, bin_info] : bin_info_map) {\n"
          "    auto post_fix_pos = name.rfind(\"_CustomKernel.bin\");\n"
          "    if (post_fix_pos == std::string::npos || post_fix_pos == 0) {\n"
          "      continue;\n"
          "    }\n"
          "\n"
          "    OM2_LOGI(\"[OM2] Begin to deserialize kernel binary '%s'\", name.c_str());\n"
          "    auto kernel_name_end_pos = name.rfind('_', post_fix_pos - 1);\n"
          "    if (kernel_name_end_pos == std::string::npos || kernel_name_end_pos == 0) {\n"
          "      OM2_LOGW(\"[OM2] Name is invalid, ignore kernel binary '%s'\", name.c_str());\n"
          "      continue;\n"
          "    }\n"
          "\n"
          "    std::string kernel_name = name.substr(0, kernel_name_end_pos);\n"
          "    OM2_LOGI(\"[OM2] Extract kernel name `%s` from '%s'\", kernel_name.c_str(), name.c_str());\n"
          "\n"
          "    // Create operator by kernel name\n"
          "    auto op = ge::CustomOpFactory::CreateOrGetCustomOp(ge::AscendString(kernel_name.c_str()));\n"
          "    if (op == nullptr) {\n"
          "      OM2_LOGE(\"[OM2] Custom op '%s' not found in registry\", kernel_name.c_str());\n"
          "      return ACL_ERROR_FAILURE;\n"
          "    }\n"
          "\n"
          "    // Cast to PortableOp\n"
          "    auto *serializable_op = dynamic_cast<ge::PortableOp *>(op);\n"
          "    if (serializable_op == nullptr) {\n"
          "      OM2_LOGE(\"[OM2] Custom op '%s' is not PortableOp\", kernel_name.c_str());\n"
          "      return ACL_ERROR_FAILURE;\n"
          "    }\n"
          "\n"
          "    // Deserialize kernel binary\n"
          "    uint8_t *data_addr = reinterpret_cast<uint8_t *>(const_cast<void *>(bin_info.data));\n"
          "    const std::vector<uint8_t> kernel_bin_buffer(data_addr, data_addr + bin_info.size);\n"
          "    const auto ret = serializable_op->Deserialize(kernel_bin_buffer);\n"
          "    if (ret != ge::GRAPH_SUCCESS) {\n"
          "      OM2_LOGE(\"[OM2] Failed to deserialize custom op '%s'\", kernel_name.c_str());\n"
          "      return ACL_ERROR_FAILURE;\n"
          "    }\n"
          "\n"
          "    OM2_LOGI(\"[OM2] Successfully deserialized custom op '%s'\", kernel_name.c_str());\n"
          "  }\n"
          "  return ACL_SUCCESS;\n"
          "}\n";
      return SUCCESS;
    default:
      output.clear();
      return FAILED;
  }
}
}  // namespace ge
